server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gt-monitor?characterEncoding=UTF-8
    username: root
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  config-location:
  mapper-locations: classpath:mapper/*Mapper.xml
